### ISSUE TITLE
Allow URIs in SR/ER strain information

### ISSUE THREAD

**Issue by jakebeal** [SD2E/experimental-intent-parser#205]
Currently the structured / experimental requests require lab IDs for strains. Over time, these need to migrate to using SynBioHub URIs instead.  The likely intermediate point is a structure that provides both (and possibly also common names from the dictionary).

The first step that needs to happen here is to allow the consumers of structured requests to support such structures.

**Comment by mwes** [comment]
Using the current SBH linking approach, I suggest the following: 

- We require users to provide linked strains as part of the ER.
- The _text_ of the linked strain entry is the lab ID, the _linked URI_ is the SBH URI

When parsing into the SR JSON, instead of outputting the list of strains as an array of strings, we should provide an array of objects, e.g.:

```
{
    "sbh_uri" : "https://hub.sd2e.org/user/sd2e/design/B_subtilis_LG227/1",
    "label" : "B_subtilis_LG227",
    "lab_id" : "name.transcriptic.B_subtilis_LG227_Colony_1"
}
```

With the label coming from the Common Name of the dictionary lookup with the provided lab id / URI.

I suspect it is currently possible to specify an invalid lab id this way. e.g. specifying some value like "foo_strain" as the text, and linking it to "https://hub.sd2e.org/user/sd2e/design/B_subtilis_LG227/1". I suggest we:

1) Verify these lookups (lab id to URI) using the dictionary to see if they exist
2) And if a lookup doesn't exist, prompt the user to verify, and if they confirm, create the mapping in the dictionary. This would significantly ease ER authorship, preventing the need for out of band strain entries in the dictionary.

**Comment by tramyn** [comment]
@mwes this makes sense. IP can definitely verify strain lookup before generating a structured request. I would make one modification to your second suggestion where IP prompts a user to verify and confirm mapping in the dictionary.  This second suggestion is already handled by IP's "Analyze from top" or "Analyze from cursor" feature. From what I understand, and @jakebeal can correct me if I am wrong, IP's analyze feature was designed to have users run-through terms in the document and make suggestions to add them to SBH if it doesn't exist. So rather go from verifying lookups to prompting users to create strain mappings in the dictionary in one API call, IP can instead make use of the analyze feature and break this up into two separate calls. To be more specific, this is what I would like to suggest when generating a structured request for the strains column:

1. Verify if the Strains (lab id to URI) using the dictionary to see if they exist
2. If the lookup doesn't exist, report in IP validation message dialog the terms that failed lookup and suggest to users to run these terms through IP's Analyze feature to have them added to SBH. 

Let me know what you think of this.

**Comment by mwes** [comment]
Your suggestion sounds good to me. Based on the current help documentation, we can currently:

- Look for _existing_ dictionary entries and suggest them as links in the document ("Analyze..")
- Look at words that are flagged by spelling, and suggest as possible entries in SBH ("Suggest additions") 
- Manually add SBH dictionary terms

In this case we already have linked terms, so analyze and suggest additions don't really make sense - analyze will only find terms that exist, and we don't need to suggest a mapping if we already have provided one. 

If the IP validation can catch the fact that there's a linked term that doesn't exist, then it sounds like the third option above will work - they can go in and add each missing strain mapping using the "Add to SynBioHub option.

**Comment by tramyn** [comment]
@mwes Great! I have created #209 to improve performance for analyzing/suggesting functions. We will try to address both these issues in 2.8 milestone.

**Comment by tramyn** [comment]
@mwes I'm looking at the SBOL dictionary spreadsheet for the Strain's tab and I do not see a lab id that follows "name.transcriptic.B_subtilis_LG227_Colony_1". Do you expect IP to prepend "name.transcriptic" to a user's input for "B_subtilis_LG227_Colony_1" to generate an SR output? "name.transcriptic" will change to the lab name that the strain will fall under in the spreadsheet. Is this correct?

**Comment by mwes** [comment]
Hi @tramyn, prepending would be the consistent/correct behavior. This is the current function that is applied to build the lab_id: https://gitlab.sd2e.org/sd2program/python-datacatalog/blob/2_2/datacatalog/formats/common.py#L436

**Comment by tramyn** [comment]
@mwes Looking at the function you provided, will the value for `lab` come from an ER document's lab table?

**Comment by mwes** [comment]
@tramyn - Yes

**Comment by tramyn** [comment]
This is ready for testing on your end @mwes . If you haven't done so, you will need to update SD2's data catalog schema to support strain objects rather than strings or sbh_uri so intent parser will past validation. 
At this point, you should be able to test this new feature out on intent parser's testing server (http://intentparser2.sd2e.org).

**Comment by mwes** [comment]
@tramyn this is producing an internal server error for the following ER: https://docs.google.com/document/d/1Mba6kqDila4W32Z46NEqXZFx868A3O36I9GIVOvMQ70

Can you take a look?

http://intentparser2.sd2e.org/document_request?1Mba6kqDila4W32Z46NEqXZFx868A3O36I9GIVOvMQ70

**Comment by tramyn** [comment]
@mwes could you try again? I made a new build with some additional fixes.

**Comment by mwes** [comment]
@tramyn This, this appears to be working now. Will need to update the ER to get the error messages to resolve.

**Comment by tramyn** [comment]
Great! Thanks @mwes

**Comment by mwes** [comment]
The generation here looks good. This can be closed from my perspective.
