### ISSUE TITLE
Request which containers to use for experiment

### ISSUE THREAD

**Issue by danbryce** [SD2E/experimental-intent-parser#220]
XPlan requires a specification for the containers to use for each experiment.  They can be of the form:

['container_search_string', 'container_search_string']
['container_id_1', 'container_id_2']
'generate'

**Comment by mwes** [comment]
@danbryce do you expect both arrays and then an additional value ('generate')? Or would the user just list out the containers of interest? If the latter, and the IP can generate this, we can pass it through to XPlan.

**Comment by danbryce** [comment]
I support three cases:

1. a list of search strings, (which if they return zero results, then try to parse as 2.)
2. a list of container ids
3. a special keywords “generate” to create new containers for the experiment.

So, you can probably treat it as a list of strings.  If the list is empty, then treat it as a “generate”.

**Comment by tramyn** [comment]
@mwes could you follow up with a schema to show me where you want this information generated from an SR? I could then add a visible field for a user to insert this information in ER document.

**Comment by tramyn** [comment]
As of last week, case 1 and 2 are supported in IP by specifying `Container Search String` as a Parameter field in a parameter table and can be accessed from IP's production server.  Case 3 is also supported but it is not included in last week's build. If Dan wants to access case 3 sooner, then I'll do a smaller 2.8.1 release. Otherwise, I will package this full feature in 2.9 release.
